name: Build and deploy Docker image to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7D0A6091E0254164BB243737B9704ED8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EAA3153A5E934DEF89D807463A5AF861 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_67A793714CC54DD292471449A794D728 }}

      - name: Build and push image
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/pptx-extractor:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/pptx-extractor:${{ github.sha }}

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ghcr.io/iius-rcox/pptx-extractor:latest
